namespace: devolutions
name: dvls
version: 1.2.1
readme: README.md
authors:
- Danny Bédard <devops@devolutions.net>
description: >
  Ansible collection for interacting with Devolutions Server (DVLS). It provides modules for authentication,
  retrieving server information and vaults, and performing create, read and update operations on secrets.
  Enables automation of common Devolutions Password Server tasks within Ansible workflows.
license:
  - MIT
tags: [dvls, secrets, devolutions, password]
dependencies: {}
repository: https://github.com/Devolutions/ansible-dvls
documentation: https://github.com/Devolutions/ansible-dvls
homepage: https://github.com/Devolutions/ansible-dvls
issues: https://github.com/Devolutions/ansible-dvls/issues
build_ignore: [.github, requirements.txt]
