name: Test module

on:
  push:
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install requests

      - name: Build
        run: ansible-galaxy collection build

      - name: Update depencencies
        run: ansible-galaxy collection install ../../devolutions-dvls-1.1.1.tar.gz --force
        working-directory: tests/integration

      - name: Run test
        run: ansible-playbook test_get-secrets.yml
        working-directory: tests/integration
